services:
  - type: web
    name: employee-attrition-backend
    env: python
    rootDir: backend
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        value: https://isgyotofnsmldgqdziui.supabase.co
      - key: SUPABASE_KEY
        sync: false
    healthCheckPath: /health
